
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUW5zT0V0cXhBM2N3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMk1UQXhOekkzTURCYUZ3MHpOakEyTURjeE56TXlNREJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNrWExwWUpJWUdkVG1ZcG5PbVRxeGl1OTFMdy9SaUs2b1dqVytlZ3E0aEdVSWVwNnR6NHk3Rm8rMU0KdmFxY0xYZ0ZUSitsTHVMaEQ0cVlIc0M2VnJFc1JZVHVNZURQOGQ5Snp0RmFnemkydVo0Y1RmUEJrR1pLL0pLZQpFTGxOamEwVVJsVi9kTG0rL21Dck9meUphOXR5bVRjcWIvWlRmVU5YRXJwQy9oSDg2dytIUy9sck5FWld4Ky91CjVWdFUwYm8zY292WXdvRFV5ajV6Nlo5Uk1pSmpuRkQ2dEd0UUFNS20vdEkxTVRUZDV3OUNBZXh1dzQ5RjBweVEKbEZTQXJvRCtGUFBIRFVPakJXZXV2a1RLUE8wbnA1OGh5WmJ3NVA4WkUyMFVEMnlnOXZSblhTOTlkbzJpcW1lZgpmWkFpdHRyNjJHS3pvRkxlaSs1NThBL1RSaVIzQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTK2tUU0JlUnV1bTZpS0NtNWpNM3M2c3BYTDZ6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnZ0dVpFT2V5YQpNcUdnTGFlb1lkRzgvZHlPQ2JXSzllQkFXeGhHNElibk84S1FXdjh2OXo0M3huWE1ZdFdXSHU3cTh3Si9KM2pNCnVqdkdQdDV1d3AzNTEvVGlWUitGa3ZPMnNxdENER0pyVUlESTl5K0ZZTkJhMDBXcE44aURJZlJSc2k1YU8wR0oKWXNZYURKVlJsRzhxUGRNMktaQmJFUU9IUzNyRFFoUnJxbDE3SXNEbmdNTENBMitzM0xKYVA4Wm9lS2EzZHVQbwpWV0I0TllMM0RERS8yN2dJeC9Ia29obG1raFBCWGZiUTZQNCsydk1ZSlFFOWF6dllvOXBwNnF0RS9KK044ckQvCmRvYU50MFdDcnBzQU9hLzE2TVNGYTJkaW9sVjNMOW9RdmptWCt0QVdHSG1Kci9oU2R3VnV5YmExZC9PTEl5RysKZ21CSk1rK2k3MjdyCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://e42a7ddb-4bea-4613-bddb-b97199137b2b.ca-central-2-gw.linodelke.net:443
  name: lke615508

users:
- name: lke615508-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjMzc2IzY1MwRl9mLUVPMEhqVi1zTXM5VGs2eU5oMTM1Y040VnAxeFh6ZU0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tZHhicW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiY2U3Y2NiZjEtOTM4NC00MTYxLWIzNTMtY2IwNTljYzkyMmZiIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.h6FVOvCwjBcXMaqMgdaF6qeNtm9fQk23GB5qMx9v9vNjz4axtCrtZqNokTwCJwC7s2FH9VbvmX1E5HIrHSmrTcHzxjTzle0JrbxOx-GKt9CcTrISZVCnGp4-RzARbn4kXNWx1_D6rc8GvHx4kuHP2I8aG00_SyAO-2EcMxGLomJt9dqRrTGcUHIa6n5dEgTWRipnAnbY_jzSlzptbfsksjVNwv8Osc1yrTULR8jC-8vhz0eUIwAxovUuaOg70ecGuZGb-tf7mZHCJM4izPifbUtMdE8H6NLnznY-PIKvnNUdBn-069EJ7zDNXbgpex-5wDuub4eYCyr6B5uEwkn1WQ

contexts:
- context:
    cluster: lke615508
    namespace: default
    user: lke615508-admin
  name: lke615508-ctx

current-context: lke615508-ctx
