
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRUcrZU4yQ0tIRVV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBMU1qWXhPREV6TlRSYUZ3MHpOakExTWpNeE9ERTROVFJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNjK3JidXpRM2wyTnBvVUFkc1Z6a0NHMUJNSmsxTGE0QThrbUY2U0h6WlhzdGJYNlpaaFB4ZjZVWFQKTEVRVFlla0JSU0dBSFV1REk5a0NxU0pwQmRxS2t0MmZGMXFoSTR5SkNLdFNvdW1vZTBmck04MVROeStJRTdlRQpmNmo1TmdLQ1h0NVZ1enZabzgyNDRiYm9qV0FnUnZ3RllUd2NaN09mWUpJTFFRR1JRN014cUk2NkdpQkRsRHZwClpQWE9oUkU3SVFLOHJwSlE0ZHFCcS9STGJsREVLc0FLWnZpN3ptMTdTQmxHVXBBaHQ3K3BJY0JZWnVieUMzNWwKM0VyYWYxbjBkaFc5NDVtbVRLdjZQa1g2UkpQT1MxVkFpbEl1T3BZNFNkejI3ZVEzQW13NnJFYkp0MU1LcUJQTwpsWVZRZUxzUi9WV1gzamVqSDVYdk4yWThuVHFUQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTWGNFTSs3RDdEdzJDbitpRzRYMTFiRVVpdllEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkVIb3dSZHBQVAoxQTFONTc3c3FjOHRmbGxKYmcvbGVmT3hLdTRTVHVvU1N2RGt5TTFTZWtUOHlQSzlTZ0NyUlA4Z05oTi9JMktDCmdHTlo4bjJZeFZGMStDZzJLakhqQjREeG12bFVQaWd6bThpVy9LMi9rYVFtdFNORDh2ZHRrdUpsbXBHMGNqcjYKSzNJc0tGb3BrZ2psTS91RDF3OGxzRkVqSjhtVG1HUS9JWWlIUTJHVlhCMWNySHlyaFVuRGtYQ1hBVmFGbU1EbApxMGdGRVVxRFFBOWViRU9nd01WQjlqSVQ0bFF3NFNDc3VmMTh1R2J1MURuemM0ZUQzR0RvY29SZXo2bFc2VWVnCmYxcFZoTWFxdFM5ZEYzbStpZE1FZ2dOQmsrVkhyWVNYdmtESTRDczliNnRRcHZ5LzlHSTFMcUNXaFdpV2ZVUm0KTlNDenJLMU9KRVlBCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://f825ba31-7eaf-4d7b-a43e-7fe5bfd136c4.ca-central-1-gw.linodelke.net:443
  name: lke608080

users:
- name: lke608080-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlpZTk56WlVETWZhQ2RWbUZjN1J1bUd4YndPbDhwdllrcjB4SmRGUTF3ZW8ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tMnhncTgiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZTI5ZjAwMWMtNTg2MC00NmQ3LTg3YzYtNmZhMjc1NzI3ZWRmIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.qkK87Joxmt5sbNjbsM2A-jITBgZSk2PBJl2ONbpwJbU3cc_y2z_EGUmmP7twcYqnVL9756TPIdf641IQFeXA4IEX9qJtlxOAYLIw8GcLCL-lMKtxYoaLHFFRtxeIGx1wiRzZ2o8dE08Vazdn1fKrpIKoGh-ouYHOZ8VcufoDGp1b3XT_ZJX4Y4NvvVbokeRhkMqo_1x0tZ6tksxIGmtZFsstCeMdKPNM6v7MwwSvpO2uBlw--KppEqdefZY46KXRwdGM8pyhd1XBEpdMAOLvcoaYDB1cfaMlqO2rpWwuCJia9AWqGTZfF-NfpRSMebcU6ZSbDSWshAeUpZFtV9nkpQ

contexts:
- context:
    cluster: lke608080
    namespace: default
    user: lke608080-admin
  name: lke608080-ctx

current-context: lke608080-ctx
